package org.grp2.gnode.api;
import io.javalin.Javalin;
import static io.javalin.apibuilder.ApiBuilder.*;
import org.grp2.gnode.api.AbstractAPI;

public class API extends AbstractAPI{

    public API(String URL, int PORT) {
        super(URL, PORT);
    }

    @Override
    public void start() {
        Javalin app = Javalin.create()
            .enableRouteOverview("/routes")
            .enableCorsForAllOrigins()
            .enableAutogeneratedEtags()
            .port(PORT);
        APIHandler handler = new APIHandler(new Gnode(URL));
        setRoutes(app, handler);
        app.start();

    }

    private void setRoutes(Javalin app, APIHandler handler) {
        app.routes(() -> {
            path("/api", () -> {
                get("/read-value/:type", handler::readValue);
                post("/write-value/:type/:value", handler::writeValue);
            });

        });
    }
}